import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Kbd } from "@/components/ui/kbd";
import { useFocusedInputTypeValue } from "@/features/editor/atoms/focus";
import { ActivityIcon, GaugeIcon, Music2Icon, Volume2Icon } from "lucide-react";

export function InputExplanation() {
  const inputType = useFocusedInputTypeValue();

  return (
    <div className="p-4 space-y-2">
      <h4 className="scroll-m-20 text-md font-semibold tracking-tight font-mono">
        Tracker usage guide
      </h4>
      <Accordion
        value={inputType ?? ""}
        type="single"
        collapsible
        className="w-full h-fit"
      >
        <AccordionItem value="note">
          <AccordionTrigger className="flex items-center gap-1.5">
            <span>Note</span>
            <Music2Icon className="size-3" />
          </AccordionTrigger>
          <AccordionContent>
            <p>
              The note input is specific to Pulse channels (channels 1, 2, and
              3). It tells the tracker what note to play at a particular point
              in time.
            </p>
            <p>
              The first character in a note is the pitch (<Kbd>A</Kbd>,{" "}
              <Kbd>B</Kbd>, <Kbd>C</Kbd>, <Kbd>D</Kbd>, <Kbd>E</Kbd>,{" "}
              <Kbd>F</Kbd>, or <Kbd>G</Kbd>). The last character is the octave.
              So <Kbd>C-5</Kbd>
              means "play a C in the 5th octave". This tracker is constrained to
              playing notes from the 2nd octave up to and including the 7th
              octave.
            </p>
            <p>
              The middle character can be <Kbd>-</Kbd>, <Kbd>#</Kbd> (for
              sharps), or <Kbd>b</Kbd> (for flats)
            </p>
            <p>
              To a row in a pulse column, you can enter the <Kbd>OFF</Kbd>{" "}
              character. This turns off the instrument.
            </p>
            <p>
              To continue the previous note, you can enter the <Kbd>---</Kbd>{" "}
              (continue) character. This keeps the note unchanged from the
              previous row.
            </p>
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="duty">
          <AccordionTrigger className="flex items-center gap-1.5">
            <span>Duty Cycle</span>
            <ActivityIcon className="size-3" />
          </AccordionTrigger>
          <AccordionContent>
            <p>
              Channels 1, 2, and 3 accept a duty cycle value. Allowed values are
            </p>
            <ul className="list-inside">
              <li>
                <Kbd>12</Kbd> → 12.5%
              </li>
              <li>
                <Kbd>25</Kbd> → 25%
              </li>
              <li>
                <Kbd>50</Kbd> → 50%
              </li>
              <li>
                <Kbd>75</Kbd> → 75%
              </li>
              <li>
                <Kbd>--</Kbd> → Retain duty cycle from previous row
              </li>
            </ul>
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="volume">
          <AccordionTrigger className="flex items-center gap-1.5">
            <span>Volume</span>
            <Volume2Icon className="size-3" />
          </AccordionTrigger>
          <AccordionContent>
            <p>
              All channels have a volume input. This input accepts any value
              from <Kbd>0</Kbd> (silent) to <Kbd>15</Kbd> (max volume).
            </p>
            <p>
              The continue character, <Kbd>--</Kbd>, can be played to keep the
              volume unchanged from the previous row.
            </p>
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="rate">
          <AccordionTrigger className="flex items-center gap-1.5">
            <span>Rate</span>
            <GaugeIcon className="size-3" />
          </AccordionTrigger>
          <AccordionContent>
            <p>
              The rate input is specific to the Noise channel. Noise is
              generated by looping a buffer of random data at a particular speed
              or rate.
            </p>
            <p>
              Slower rates sound more like a below while faster rates produce a
              hiss sound.
            </p>
            <p>
              The rate can be set to any value between <Kbd>0</Kbd> (effectively
              "off") and <Kbd>99</Kbd>
            </p>
            <p>
              The value entered gets turned into a decimal value. So an input of{" "}
              <Kbd>34</Kbd> gets interpreted as "set the buffer playback rate to
              3.4x speed".
            </p>
          </AccordionContent>
        </AccordionItem>
      </Accordion>
    </div>
  );
}
